model_path: robot_groundcontact.xml

pos: [0.0, 0.0, 0.12]
quat: [1.0, 0.0, 0.0, 0.0]

joint_names:
  - left_hip_yaw
  - left_hip_roll
  - left_hip_pitch
  - left_knee
  - left_ankle
  - neck_pitch
  - head_pitch
  - head_yaw
  - head_roll
  - right_hip_yaw
  - right_hip_roll
  - right_hip_pitch
  - right_knee
  - right_ankle

default_joint_pos:
  - 0.0
  - -0.0873
  - -0.4579
  - -0.0049
  - 0.4530
  - 0.3491
  - 0.3491
  - 0.0
  - 0.0
  - 0.0
  - 0.0873
  - 0.4579
  - 0.0049
  - -0.4530

kp: 0.55
kv: 0.0
effort_limit: 0.96