model_path: robot_groundcontact.xml

pos: [0.0, 0.0, 0.12]
quat: [1.0, 0.0, 0.0, 0.0]

joints:
  - name: left_hip_yaw
    default_pos: 0.0
  - name: left_hip_roll
    default_pos: -0.0873
  - name: left_hip_pitch
    default_pos: -0.4579
  - name: left_knee
    default_pos: -0.0049
  - name: left_ankle
    default_pos: 0.4530
  - name: neck_pitch
    default_pos: 0.3491
  - name: head_pitch
    default_pos: 0.3491
  - name: head_yaw
    default_pos: 0.0
  - name: head_roll
    default_pos: 0.0
  - name: right_hip_yaw
    default_pos: 0.0
  - name: right_hip_roll
    default_pos: 0.0873
  - name: right_hip_pitch
    default_pos: 0.4579
  - name: right_knee
    default_pos: 0.0049
  - name: right_ankle
    default_pos: -0.4530

kp: 0.55
kv: 0.0
effort_limit: 0.96

feet_link_names: [ankle_left, ankle_right]
contact_force_threshold: 1.0      # N; standing load is ~3.6 N per foot